### PR TITLE
Frank Schroeder's DB source + scroll limits applied

### PR DESCRIPTION
**Pull request by michaeltyson**
I've applied Frank Schroeder's patch, which includes the scroll limits code, from [zontar's version](http://route-me-map.googlegroups.com/web/route-me-MapView-trunk-dbtilesource-scroll-limit.tar.gz?hl=en&gda=RrJCnmkAAADoaYbwQwGZ6YtoN9z2SBFN1QCEpatwO1QNfV1GaDw7cHZml2p7HNpNecjwXhLT4XQ0bKrgvt64zbMaYVLNcuQPVLem5GP8a5tbUrGPN8cfA2P4FLggfM98zR_mohFbynSECKgQbmraGdxlZulaYnsh), dated Sep 11.

I made a minor change (the 2nd commit) to RMMapView's moveBy, to clamp instead of performing a noop when the scroll would move beyond the bounds - this gives smoother panning.

### CODE REVIEW

**Comment by vyskocil** [comment]
The code seems ok for me and it's good things to have in trunk.

**Comment by michaeltyson** [comment]
Cheers Vlad =) Would you like me to do the merge? (The instructions below are wrong, BTW, as I discovered yesterday; you actually need to follow the ones at http://help.github.com/pull-requests/)

**Comment by vyskocil** [comment]
Yes, you can do it, I'm not yet very fluent with GIT and github. I'll read the help page :)

**Comment by michaeltyson** [comment]
Righto, no problem =)

**Pull request merged**
