### PR TITLE
Automatic marker ordering

### PR DESCRIPTION
**Pull request by clarketus**
Hey there

I am using the route-me library in a project, and have found that markers need to be manually ordered.

This commit will make markers get automatically ordered based on vertical map position, and also puts them above other layers on the map to ensure that they look nice and are always available to receive touch events.

Was hoping this could be pulled into master if you agree that the functionality is required? Am also happy to receive suggestions/changes to this code.

### CODE REVIEW

**Comment by amjaliks** [comment]
I think it is a great addition. But it needs some small fixes.

**Comment by clarketus** [comment]
Have fixed the requested issues. 

I rebased my forks master against your master and force pushed, so the comments and my answers are no longer in the commit above, but heres a URL to the old commit, so you can see my answers to your questions:

https://github.com/clarketus/route-me/commit/7c658e64aae729f36e3cfea357d0df60f372dda6#commitcomment-307964

This should be all good to go now?

**Comment by vyskocil** [comment]
I think that the ordering shouldn't be called automatically in addSublayer because one may not want it for example if a RMPath, RMCircle,... or other overlay should be in front of the markers, this may also rise performance issues with lot of layers and the ordering could already be done otherwise, for example in my application I use the zPosition layer attribute.
We can merge the orderLayers method but I'm not in favor to call it automatically.

**Comment by clarketus** [comment]
I have no issue removing the orderLayers call from addSublayer. I understand peoples use of this will differ per project, but for me, as i am just using markers, being able to call orderLayers once after marker addition will be very useful.

**Comment by clarketus** [comment]
so we should be all good to go now?

**Comment by vyskocil** [comment]
Ok, I just merged it. 
Thank you.

**Pull request merged**
