### PR TITLE
Implementation of user location visualization

### PR DESCRIPTION
**Pull request by hwiesmann**
The pull request includes the visualization of the user's location and the implementation of a demonstration of the new feature in ProgrammaticMap.

The visualization of the user's location is similar to the implementation of MKMapView. A marker shows the location and a circle the accuracy of the location determination.
The user's location can be shown and hidden. Furthermore, it can be checked if the user's location is currently visible on the map.

The ProgrammaticMap sample has been used to show the new implementation as it currently does not do anything useful but showing how to implement route-me programmatically. Actually the sample has been further modified to show a real programmatic implementation as it currently shows a mix of nib files and a programmatic implementation.

### CODE REVIEW

**Comment by meersmans** [comment]
Where can i see a sample of this visualization? is it just the same as the maps.app?

Edit: saw it on your profile with the ProgrammaticMap ... :) Do yo think you can fix it that it's just the same as in maps.app with the bling of the marker and the circle?... Would be nice!

**Comment by hwiesmann** [comment]
I can try it but it has currently not my highest priority.

My question is: what is the meaning of the increasing circle around the marker? It looks nice but does it also have a meaning?
I though it has something to do with getting a location update but it seems to be independent of it.

**Comment by meersmans** [comment]
@hwiesmann the circle in the maps.app is about the accuracy of the gps signal... Do you think you can make a look-a-like of that? That would be nice!

**Comment by hwiesmann** [comment]
Hi,

The circle representing the accuracy is already implemented. Depending on the last obtained accuracy the circle's diameter is changed.
But I thought you meant the "echoing" (sonar like) continuously increasing circle that is shown additionally in the maps app. I have no idea what the meaning of this feature is (besides indicating that the app is still alive).

**Comment by meersmans** [comment]
Indeed that feature has no meaning... but it would be really cool if you could implement that! Looks nice...

**Comment by afarnham** [comment]
The meaning is that you currently have a highly accurate and updating signal of your current location. I believe it only does the increasing circle when the CoreLocation horizontal accuracy of location updates is >= 10 meters

**Comment by incanus** [comment]
I'm seeing a behavior where the dot is shown until you zoom in a bit, then it is replaced with a two-town `RMCircle`, but never goes back to showing the dot image. Is this intended behavior?

**Comment by hwiesmann** [comment]
No, this is not intended behavior. But I cannot reproduce it. You do not see this in the demo I submitted, or?
I am not sure if this is a bug in my implementation. The problem might be that I am using the built-in methods to show the marker. If at some point all markers are removed the location marker will also be removed (due to a bug in RMMarkerManager also the circle will be removed when calling hideAllMarkers).
This is some kind of "bug" but I did not implement a workaround for it because especially in the RMMarkerManager and RMLayerCollection source code a lot of methods are marked as deprecated and I do not know what will replace them. Especially, I do not know the future of RMMarkerManager and RMLayerCollection (why is there no overlay manager, btw?). So, if somebody tells me what remains and what will disappear I will make sure that accidental removal will not take place.

**Comment by carlosefonseca** [comment]
I think the location marker should be fully opaque and the outer circle should be in a different kind of blue.

**Comment by michaeltyson** [comment]
Closing this one for now, as there appear to be outstanding issues.

**Pull request closed without merging**
