### PR TITLE
Framework builds

### PR DESCRIPTION
**Pull request by sethfitz**
This patchset creates a `PROJ.4.framework` build (to replace the `libProj4.a` target, which is still present) that creates a universal (_arm_ + _i386_) framework suitable for dropping into arbitrary projects.

It also simplifies the existing `MapView.framework` build, changes MapView's dependency from `libProj4.a` to `PROJ.4.framework` by updating pointers to PROJ.4's headers, and updates the unit test application to use the built framework rather than compiling and linking directly to the source (to put it more in line with an end-user's use of it).

(Aside: I can't actually get the unit test app to run...)

Finally, it updates the `SampleMap`, `ProgrammaticMap`, and `MarkerMurder` sample apps to use the framework builds.  These now run where I was previously encountering errors about missing symbols.

This pull request includes the contents of the "iOS 4.x update" request.

### CODE REVIEW

**Comment by amjaliks** [comment]
What's wrong with static library?

**Comment by sethfitz** [comment]
Nothing, though something about the existing build (out of the box) is stripping symbols and preventing the sample apps from compiling.

It's slightly easier to embed (and statically link) frameworks, as you can ship them as a single bundle, headers and all (much like OS X frameworks).  Most people using route-me are probably tweaking the source, but for those that aren't, providing a single download that Xcode understands is more convenient.

Mainly I'm just biased towards frameworks and find them easier to work with.

**Comment by hjon** [comment]
I'm going to bring this up on the mailing list to see if we can get opinions from others. I wouldn't mind the convenience of a framework, but on the other hand, I'm also one of those who is tweaking the source. :-)

**Comment by ns-1m** [comment]
I think if would be good to have a projection framework. I think we just tag it with the proj version (eg. Proj4.7.0.framework).

**Comment by amjaliks** [comment]
Please, discuss it on mailing list, thus, we keep opinion on one place: http://groups.google.com/group/route-me-map/browse_thread/thread/2a5fcc1fd6b3fd22

**Comment by michaeltyson** [comment]
Looks like this one's gone a bit stale: Closing it for now. Feel free to reopen if interest's still there.

**Pull request closed without merging**
