### PR TITLE
RMPath rewrite

### PR DESCRIPTION
**Pull request by michaeltyson**
This is the RMPath rewrite I did last year for my app - it's still in use, and works better for me than the implementation currently in the main branch.
- Much more efficient; rendered in the background on a CALayer within view bounds - dramatically faster for long paths
- Cleaner implementation with revised geometry
- Direct access to path, for hit testing, etc
- Projected bounds accessor

### CODE REVIEW

**Comment by tracyharton** [comment]
Works better for me, as well, and I haven't encountered any issues...

**Comment by michaeltyson** [comment]
Thanks Tracy! (and thanks for all your work!)

**Comment by rpcarver** [comment]
Works wonderfully for me!   Solved a couple of issues I was waiting till I had some more round tuits to dig in and fix.   Thanks!

**Comment by michaeltyson** [comment]
Great - well, I'm going to take this as sufficient endorsement and merge this bad boy. Here goes!

**Comment by incanus** [comment]
This commit got rid of path shadows, line cap & line join, drawing mode...

**Comment by tracyharton** [comment]
Well, that's a pisser

**Comment by michaeltyson** [comment]
Pretty easy to add back though. I'll take a look soon.

**Comment by michaeltyson** [comment]
See Pull #169.

**Comment by andrewljohnson** [comment]
Does anyone else experience memory spikes and crashes occasionally, when zooming in quickly on a mapView with paths showing?

**Pull request merged**
