### PR TITLE
Added category NSUserDefaults (RouteMe) with methods for work with RMProjectedPoint and RMProjectedRect

### PR DESCRIPTION
**Pull request by amjaliks**
Want to here you opinion about such addition, before I pull it to RM.

### CODE REVIEW

**Comment by CmputrAce** [comment]
I'm not sure how the routines are associated with NSUserDefaults, but it may be my own lack of understanding. Does this extension provide storage for / access to user defaults choices to be saved between sessions? I use NSUserDefaults in my RTAppSettings class to maintain user settings from my SettingsViewController, but from what I can tell, your extension provides "live" values. Is this correct, or is my understanding flawed?

**Comment by amjaliks** [comment]
I use these extensions to store map state between app launches, thus, I can restore the same state (also the same visible map region) next a user starts an app.

**Comment by CmputrAce** [comment]
cool

**Comment by michaeltyson** [comment]
I certainly don't see any reason not to add this in - looks like a useful utility

**Pull request merged**
